---
title: "Submarines around the world"
output: 
  html_document:
    toc: FALSE
---



# What is it?

As the name suggests, this website aims to become a comprehensive catalog of submarines throughout history. Looking at minor and major submarine operators since the late 19th century to today. This will be through graphical summaries of service timelines. Various classes will be used using to scale illustrations from the excellent Shipbucket website. 

[shipbucket.com](http://www.shipbucket.com/)

Secondarily, I will cover submarine statistics of world war 2, sourcing data on successes from three somewhat old but major data reference books:

*Allied Submarine Attacks of World War Two* by Jürgen Rohwer

*Axis Submarine Successes of World War Two* by Jürgen Rohwer

*United States and Allied Submarine Successes in the Pacific and Far East During World War II* by John D. Alden and Craig R. McDonald

## Caveats

This is work at very early stages of progress

This website will not cover midget submarines in the countries list as data for these at the individual level is often non-existent or very unreliable. However, they will be covered for their world war II results. A number of countries similarly have incomplete or unreliable data, but approximate dates will be used for these.

## Updates

2025-02-14: Added Bangladesh and Brazil

2024-11-18: website launche


